Repository Health-Education-England/hee-cms-platform, pull requests merged in 2022-12, with the labels that each got.

#281 NWPS-1088 & NWPS-1089: Phone number validations
  cms/src/main/java/uk/nhs/hee/web/validation/validator/PhoneNumberValidator.java
  cms/src/main/java/uk/nhs/hee/web/validation/validator/WebsiteUrlValidator.java
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/update/registry/ReplaceHEElogoToNull.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/update/registry/UpdatePhoneNumberWithPrefix.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/person.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
Labels: enhancement

#279 NWPS-1136 create a publication landing page
  cms/src/main/resources/org/hippoecm/frontend/plugins/yui/upload/validation/DefaultUploadValidationService.properties
  repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-publication-landingpage-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-publication-landingpage-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage/prototypes/prototype/documentVersions/hippo-resource
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage/prototypes/prototype/languageVersions/hippo-resource
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationResource.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationResource/prototypes/prototype/hippo-resource
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationprofessions.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationtopics.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationtypes.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/careers/higher-specialist-scientist-training---publication-landing/higher-specialist-scientist-training---publication-landing[1]/documentVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/careers/higher-specialist-scientist-training---publication-landing/higher-specialist-scientist-training---publication-landing[1]/languageVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/careers/higher-specialist-scientist-training---publication-landing/higher-specialist-scientist-training---publication-landing[2]/documentVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/careers/higher-specialist-scientist-training---publication-landing/higher-specialist-scientist-training---publication-landing[2]/languageVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/careers/higher-specialist-scientist-training---publication-landing/higher-specialist-scientist-training---publication-landing[3]/documentVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/careers/higher-specialist-scientist-training---publication-landing/higher-specialist-scientist-training---publication-landing[3]/languageVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/documentVersions/Reasonable-Adjustments-Policy-October-2022.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/documentVersions/Reasonable-Adjustments-form.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/documentVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/documentVersions[1]/Reasonable-Adjustments-Policy-October-2022.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/documentVersions[2]/Reasonable-Adjustments-form.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/languageVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/languageVersions/sample-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[1]/languageVersions/sample.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[2]/documentVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[2]/documentVersions[1]/Reasonable-Adjustments-Policy-October-2022.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[2]/documentVersions[2]/Reasonable-Adjustments-form.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[2]/languageVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[2]/languageVersions/sample-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[2]/languageVersions/sample.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[3]/documentVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[3]/documentVersions[1]/Reasonable-Adjustments-Policy-October-2022.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[3]/documentVersions[2]/Reasonable-Adjustments-form.odt
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[3]/languageVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[3]/languageVersions/sample-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications/2022/policies/reasonable-adjustments-policy---publication-landing/reasonable-adjustments-policy---publication-landing[3]/languageVersions/sample.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/reports.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-higher-specialist-scientist-training-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-higher-specialist-scientist-training-web-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-reasonable-adjustments-policy-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-reasonable-adjustments-policy-web1-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-reasonable-adjustments-policy-web2-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/annual-reports-and-accounts-2020-21.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/publications.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/utils/date-util.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/PublicationLandingPage.java
  site/components/src/main/java/uk/nhs/hee/web/beans/Report.java
  site/components/src/main/java/uk/nhs/hee/web/components/PublicationLandingPageComponent.java
  site/components/src/main/java/uk/nhs/hee/web/components/info/MultiOrgLogoComponentInfo.java
  site/components/src/main/java/uk/nhs/hee/web/components/info/PublicationLandingPageComponentInfo.java
Labels: enhancement

#299 NWPS-1088-Person-Content-Type-Design-Updates
  repository-data/application/src/main/resources/hcm-config/configuration/update/registry/MigratePersonPronouns.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/update/registry/UpdateTwitterwithLinkUrl.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-contact.ftl
Labels: enhancement

#303 NWPS-1276: Publication and Publication landing page content model and template updates
  cms/src/main/java/uk/nhs/hee/web/validation/validator/MandatoryPublicationProfessionsOrTopicsValidator.java
  cms/src/main/java/uk/nhs/hee/web/validation/validator/NumericValidator.java
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationtopics.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationtypes.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
Labels: enhancement, bugfix

#305 NWPS-1219 & NWPS-1328: FE tidied up CSS & JS integration
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
Labels: front-end

#309 NWPS-1273-Rename-Document-Types-Adding-Page-Prefix
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
Labels: enhancement

#308 NWPS-1338-Alignment-Nations-Logos-CSS-Changes
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
Labels: enhancement

#298 NWPS-1124: [channel-specific] Publication listing/collection page implementation
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-publicationListingPage-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-publicationListingPage-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationListingPage.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/listing.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-contentpage.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/checkbox-group-with-filter-count.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/PublicationListingPage.java
  site/components/src/main/java/uk/nhs/hee/web/components/ListingPageType.java
  site/components/src/main/java/uk/nhs/hee/web/components/PublicationListingPageComponent.java
  site/components/src/main/java/uk/nhs/hee/web/components/info/PublicationListingPageComponentInfo.java
  site/components/src/main/java/uk/nhs/hee/web/repository/HEEField.java
  site/components/src/main/java/uk/nhs/hee/web/repository/ValueListIdentifier.java
  site/components/src/test/java/uk/nhs/hee/web/components/ListingPageTypeTest.java
  site/components/src/test/java/uk/nhs/hee/web/repository/HEEFieldTest.java
  site/components/src/test/java/uk/nhs/hee/web/repository/ValueListIdentifierTest.java
Labels: enhancement

#306 NWPS-1088 & NWPS-1089: Latest person/department updates
  cms/src/main/java/uk/nhs/hee/web/validation/validator/PhoneNumberValidator.java
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/update/registry/RemoveUKCountryCodeFromPhoneNumbers.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/person.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-contact.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/utils/phone-number-util.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/Person.java
Labels: enhancement
