Repository Health-Education-England/hee-cms-platform, pull requests merged in 2022-11, with the labels that each got.

#282 NWPS-1187-Page-Metadata-bugfix-resolving-null-values-entry
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/block-links.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/include/page-meta-data.ftl
Labels: WIP, bugfix

#283 NWPS-1003 header changes logos menu search results
  repository-data/application/src/main/resources/hcm-config/configuration/update/registry/ReplaceHEElogoToNull.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/logotypes.yaml
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/css/hee_custom_backend.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/multi-org-logo.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-cookies-banner.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-header.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-menu.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-top.ftl
  site/webapp/src/main/webapp/static/assets/images/logos/hee-logo.png
  site/webapp/src/main/webapp/static/assets/images/logos/heiw-logo.png
  site/webapp/src/main/webapp/static/assets/images/logos/nhs-scotland-logo.png
  site/webapp/src/main/webapp/static/assets/images/logos/nimdta-logo.png
  site/webapp/src/main/webapp/static/js/hee.min.js
Labels: enhancement, front-end

#286 NWPS-1003: Moving 'multi-org-logo' container specific CSS classes onto 'cms-request.css' for consistency
  repository-data/webfiles/src/main/resources/site/css/cms-request.css
  repository-data/webfiles/src/main/resources/site/css/hee_custom_backend.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
Labels: enhancement

#287 NWPS-1250: Department content model update for release version 1
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/Department.java
Labels: enhancement

#277 NWPS-1089 - Department Content Type - Enhancement
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/Department.java
Labels: enhancement

#292 NWPS-1250: Removal of URL validation for Department 'Website' field
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/department.yaml
Labels: enhancement

#294 NWPS-1003: [tidy-up] 'Health Education England' logo data tidyup
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
Labels: enhancement
