Repository Health-Education-England/hee-cms-platform, pull requests merged in 2023-03, with the labels that each got.

#365 [NWPS-1090] Old contact card (hee:contactCard) template query tidy-up
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-contact-card.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-document.yaml
Labels: bugfix

#362 [NWPS-1346] Publication landing page validator and workflow updates
  cms/src/main/java/uk/nhs/hee/web/repository/documentworkflow/DocumentWorkflowImplWithoutCopyOperation.java
  cms/src/main/java/uk/nhs/hee/web/validation/validator/UniqueWebPublicationsValidator.java
  cms/src/test/java/uk/nhs/hee/web/repository/documentworkflow/DocumentWorkflowImplWithoutCopyOperationTest.java
  cms/src/test/java/uk/nhs/hee/web/validation/validator/UniqueWebPublicationsValidatorTest.java
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/workflows/default.yaml
Labels: bugfix

#358 [NWPS-1222] Upgrading CMS to 14.7.13
  README.md
  pom.xml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/forms.yaml
Labels: upgrade

#371 [NWPS-1411-1424-1425-1427] Adding compounds to Content Blocks - News & Blogs
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/news.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
Labels: enhancement
