Repository Health-Education-England/hee-cms-platform, pull requests merged in 2023-07, with the labels that each got.

#433 [NWPS-1377-1580] Updated CSS & JS to NHS Frontend version 7.0.0
  README.md
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/css/nhsuk-4.1.min.css
  repository-data/webfiles/src/main/resources/site/css/nhsuk-7.0.0.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/atozlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/casestudylisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/categorybasedlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/eventlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchbanklisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/eforms/eforms.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-breadcrumb.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-cookies-banner.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-menu.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-top.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/action-link.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/back-link.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/block-links.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/button.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/cta-card.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/last-next-reviewed-date.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/newsletter-subscribe-form.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/statement-card.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/include/cookie-button.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/include/pagination-nhs.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.js
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
  repository-data/webfiles/src/main/resources/site/js/nhsuk-4.1.0.min.js
  repository-data/webfiles/src/main/resources/site/js/nhsuk-7.0.0.min.js
  site/webapp/src/main/webapp/static/assets/icons/icon-arrow-left.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-arrow-right-circle.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-arrow-right.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-chevron-left.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-chevron-right.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-close.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-cross.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-minus.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-plus.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-search.svg
  site/webapp/src/main/webapp/static/assets/icons/icon-tick.svg
  site/webapp/src/main/webapp/static/assets/logos/logo-nhs.svg
Labels: upgrade

#461 NWPS-1520-BE-Publication-collections-filters-need-to-be-in-alphabetic…
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/checkbox-group-with-filter-count.ftl
  site/components/src/main/java/uk/nhs/hee/web/components/PublicationListingPageComponent.java
Labels: enhancement

#462 NWPS-1559-be-publication-landing-page-language-and-doc-version
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/assetResource.yaml
Labels: enhancement

#460 [NWPS-1374] Link picker configuration update for `assetData` field of `assetResource` compound type
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/assetResource.yaml
Labels: enhancement

#463 NWPS-1507-BE-Inset-text-on-news-articles-and-blog-posts
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
Labels: enhancement

#480 [NWPS-1550] Removal of `hee:rightHandImage` template queries to restrict the creation of its documents
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-rightHandImage-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-rightHandImage-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
Labels: bugfix

#475 [NWPS-1653] Fix for broken component icons in the experience manager
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/expert-searching-blog-page.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/default/catalog.yaml
Labels: bugfix

#478 [NWPS-1658] Publication landing and single page fixes
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
Labels: bugfix

#483 [NWPS-1662] Removal of the unused `pagenotfound` container
  repository-data/site/src/main/resources/hcm-config/hst/blueprints/website-blueprint/configuration.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/pagenotfound.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/dental/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/digital-transformation/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/health-careers/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/kls/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/lks/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/quality/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/pagenotfound-main.ftl
Labels: bugfix

#488 [NWPS-1637] [WIP] Training home page updates
  cms/src/main/resources/ckeditor/styles_without_h1-h2.js
  cms/src/main/resources/ckeditor/styles_without_h1.js
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/tabPanel.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hippostd/html.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/training-pages.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammesHomePage-main.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammesHomepage.java
Labels: enhancement, WIP

#486 [NWPS-1523] Deleting the training programme page dev data from `repository-data/application`
  repository-data/application/src/main/resources/hcm-content/content/documents/lks/training-programmes-pages.yaml
Labels: bugfix

#495 [NWPS-1662] [Recreated] Removal of the unused `pagenotfound` container
  repository-data/site/src/main/resources/hcm-config/hst/blueprints/website-blueprint/configuration.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/pagenotfound.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/dental/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/digital-transformation/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/feedback/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/health-careers/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/kls/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/lks/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/medical/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/quality/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/website-testing/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/pagenotfound-main.ftl
Labels: bugfix

#481 [NWPS-1660] Fix for Mini-hub rendering errors when the associated SCPs are offline
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/include/page-meta-data.ftl
  site/components/src/main/java/uk/nhs/hee/web/components/MiniHubComponent.java
Labels: bugfix

#476 [NWPS-1655] Fix for `Bean Writer` tool error for content-block based beans
  site/components/src/main/java/uk/nhs/hee/web/beans/BlogPost.java
  site/components/src/main/java/uk/nhs/hee/web/beans/Guidance.java
  site/components/src/main/java/uk/nhs/hee/web/beans/HomePage.java
  site/components/src/main/java/uk/nhs/hee/web/beans/LandingPage.java
  site/components/src/main/java/uk/nhs/hee/web/beans/News.java
  site/components/src/main/java/uk/nhs/hee/web/beans/PublicationLandingPage.java
  site/components/src/main/java/uk/nhs/hee/web/beans/Report.java
  site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammePage.java
  site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammesHomepage.java
Labels: bugfix
