Repository Health-Education-England/hee-cms-platform, pull requests merged in 2023-02, with the labels that each got.

#344 [NWPS-1383] FE integration to stop Author image repeating/tiling
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
Labels: front-end, bugfix

#335 [NWPS-1274] Renaming Content Blocks
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
Labels: enhancement

#347 NWPS-1234: Initial visual regression content and Backstop config setup
  .gitignore
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-blog-post-page-blog-page.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-home-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-landing-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-mini-hub-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-news-article-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-scp-cookies-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-scp-newsletter-signup-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-standard-content-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/visual-regression.yaml
  visual-regression/README.md
  visual-regression/backstop.js
Labels: enhancement

#345 [NWPS-1342] Enhancement/nwps 1342 fei publications collections
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/select.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.js
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
Labels: enhancement

#353 [NWPS-1403-1382] Publication collection bug fixes
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/js/hee.js
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
Labels: bugfix

#346 [NWPS-1384] GPNRO-Prod Redirect setup & updating prod URL redirection changes
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain_with_preview.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain_with_preview.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/digital-transformation/shorteneddigitalacademy.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/medical/gpnrotomedicalgpredirects.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/website-testing.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/website-testing/redirecttospecialtylandingpage.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/website-testing/searchtosearchresultsredirect.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live-redirect/uk.yaml
Labels: enhancement

#352 [NWPS-1144] Inclusion of Publication landing pages in search results
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/documenttypes.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/listing-pages.yaml
  site/components/src/main/java/uk/nhs/hee/web/components/SearchResultsComponent.java
Labels: enhancement

#355 [NWPS-1234] Docker-based backstop visual regression setup
  repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-localhost/internal.yaml
  visual-regression/README.md
  visual-regression/backstop.js
Labels: enhancement

#356 [NWPS-1405] Author name not captured on search results bugfix
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
Labels: bugfix

#357 [NWPS-1274] Content block name changes
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
Labels: enhancement

#360 [NWPS-1234] Separating docker virtual localhost
  repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-localhost-docker.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-localhost-docker/internal.yaml
Labels: enhancement

#359 [NWPS-1090] Update contact component and allow addition of description
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-contact-card-description.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/HomePage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/contactCardWithDescription.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/contactCardWithDescriptionReference.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/lks/contact-card-summary-one.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/components.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/contact-card-with-description.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/contact-card.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/department-contact.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-contact.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/ContactCardWithDescription.java
  site/components/src/main/java/uk/nhs/hee/web/beans/ContactCardWithDescriptionReference.java
Labels: enhancement

#354 [NWPS-1346] Unique web publications validator implementation
  cms/src/main/java/uk/nhs/hee/web/utils/ChannelUtils.java
  cms/src/main/java/uk/nhs/hee/web/utils/DocumentUtils.java
  cms/src/main/java/uk/nhs/hee/web/validation/validator/UniqueAuthorValidator.java
  cms/src/main/java/uk/nhs/hee/web/validation/validator/UniqueWebPublicationsValidator.java
  cms/src/test/java/uk/nhs/hee/web/utils/ChannelUtilsTest.java
  cms/src/test/java/uk/nhs/hee/web/utils/DocumentUtilsTest.java
  cms/src/test/java/uk/nhs/hee/web/validation/validator/UniqueWebPublicationsValidatorTest.java
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
Labels: enhancement
