Repository Health-Education-England/hee-cms-platform, pull requests merged in 2023-06, with the labels that each got.

#431 [NWPS-1578] Plugin upgrade
  pom.xml
Labels: upgrade

#437 [NWPS-1514] Replaced `management/Management` with `management_professionals/Management professionals`
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/publicationprofessions.yaml
Labels: enhancement

#440 [NWPS-1503] Publication landing page other format text on page
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/assetResource.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/PublicationLandingPage.java
  site/components/src/main/java/uk/nhs/hee/web/beans/Report.java
Labels: enhancement

#442 [NWPS-1364] Page not found template tidy-up
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/pagenotfound-main.ftl
  visual-regression/backstop.js
Labels: enhancement, front-end

#425 [NWPS-1522] Work for the new training journey box
  cms/src/main/java/uk/nhs/hee/web/validation/validator/MandatoryTrainingJourneyValidator.java
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammePage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammePage.java
Labels: enhancement

#404 [NWPS-1135] Feature/nwps 1135 be new featured content component
  cms/src/main/java/uk/nhs/hee/web/selection/frontend/provider/PublicationTypeNameProviderForFeaturedContent.java
  cms/src/main/java/uk/nhs/hee/web/validation/validator/MandatoryFeaturedDocumentsValidator.java
  cms/src/main/java/uk/nhs/hee/web/validation/validator/MandatoryFeaturedMethodValidator.java
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-featuredContent-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-featuredContent-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/featuredContent.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/featuredContentReference.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/featuredcontenttypes.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/landing-pages.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/components.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/featured-content.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/FeaturedContent.java
  site/components/src/main/java/uk/nhs/hee/web/beans/FeaturedContentReference.java
  site/components/src/main/java/uk/nhs/hee/web/beans/Report.java
  site/components/src/main/java/uk/nhs/hee/web/components/ReportComponent.java
  site/components/src/main/java/uk/nhs/hee/web/services/FeaturedContentBlockService.java
  site/components/src/main/java/uk/nhs/hee/web/services/enums/FeaturedContentMethod.java
  site/components/src/main/java/uk/nhs/hee/web/utils/QueryAndFiltersUtils.java
Labels: enhancement

#450 [Housekeeping] Fix for `The entity name must immediately follow the '&' in the entity reference`
  repository-data/webfiles/src/main/resources/site/freemarker/include/page-meta-data.ftl
Labels: bugfix

#453 [NWPS-1475] Anchorlinks sticky javascript assets change
  repository-data/webfiles/src/main/resources/site/js/hee.js
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
Labels: bugfix

#426 [NWPS-1234] [WIP] Collection tidy-up integration
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/listing.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page/documentVersions/STP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page/documentVersions/STP-Monthly-Memo.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page/documentVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page/languageVersions/ETP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page/languageVersions/ETP-Monthly-Memo.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page/languageVersions/hippo-resource
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[1]/documentVersions/STP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[1]/documentVersions/STP-Monthly-Memo.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[1]/languageVersions/ETP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[1]/languageVersions/ETP-Monthly-Memo.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[2]/documentVersions/STP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[2]/documentVersions/STP-Monthly-Memo.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[2]/languageVersions/ETP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[2]/languageVersions/ETP-Monthly-Memo.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[3]/documentVersions/STP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[3]/documentVersions/STP-Monthly-Memo.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[3]/languageVersions/ETP-Monthly-Memo-1.pdf
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression/vr-publication-landing-page/vr-publication-landing-page[3]/languageVersions/ETP-Monthly-Memo.pdf
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-a-z-listing-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-blog-post-collection-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-bulletin-collection-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-case-study-collection-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-event-collection-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-news-article-collection-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-publication-collection-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-search-bank-collection-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-collection-and-listing-pages-vr-search-listing-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-blog-post-page-blog-page.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-home-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-landing-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-mini-hub-page-minihub-page.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-news-article-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-publication-landing-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-publication-landing-page-vr-publication-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-scp-cookies-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-scp-newsletter-signup-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-content-pages-vr-standard-content-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/visual-regression.yaml
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/casestudylisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/categorybasedlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/eventlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchbanklisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/pagenotfound-main.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.js
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
  site/components/src/main/java/uk/nhs/hee/web/components/SearchResultsComponent.java
  visual-regression/backstop.js
Labels: WIP, front-end

#430 [NWPS-1412] Integration of media embed display issue fixes
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/global.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/last-next-reviewed-date.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/media.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.js
Labels: front-end
