Repository Health-Education-England/hee-cms-platform, pull requests merged in 2023-10, with the labels that each got.

#562 [NWPS-1755] Upgrade to brXM 15.3.2 with updated pom and readme files
  README.md
  pom.xml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
Labels: upgrade

#566 [NWPS-1764] Making the `header` field optional on navigation cards (aka content cards) content block
  cms/src/main/java/uk/nhs/hee/web/validation/validator/ContentCardContentBlockValidator.java
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
Labels: bugfix

#565 [NWPS-841] Channel specific `page not found` (404) page build
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/pagenotfound.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/dental/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/digital-transformation/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/feedback/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/health-careers/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/kls/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/lks/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/medical/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/quality/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/website-testing/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/wte-alpha/settings.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/dental/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/digital-transformation/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/feedback/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/health-careers/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/kls/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/medical/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/quality/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/website-testing/settings/pages/page-not-found.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/wte-alpha/settings/pages/page-not-found.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/pagenotfound.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/pagenotfound-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/include/page-meta-data.ftl
  site/components/src/main/java/uk/nhs/hee/web/components/PageNotFoundComponent.java
Labels: enhancement

#564 [NWPS-1685] FE technical debt remaining training programme information
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.js
Labels: front-end

#563 [NWPS-1721-1722] Adding details and expander content blocks to news a…
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/news.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
Labels: enhancement

#568 [NWPS-1762] Publication collection taxonomy list sort order bug fix
  site/components/src/main/java/uk/nhs/hee/web/components/PublicationListingPageComponent.java
Labels: bugfix

#570 [NWPS-841] Fix to remove additional bottom space on the main section of the landing page
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/landingPage-main.ftl
Labels: bugfix

#573 [NWPS-1774] Freemarker fixes
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammesHomePage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/details.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/external-links-card.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/image-block.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/media.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/table.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/tabs.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/warning-callout.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
Labels: bugfix
