Repository Health-Education-England/hee-cms-platform, pull requests merged in 2023-01, with the labels that each got.

#317 NWPS-1124: [channel-specific] Publication listing/collection page implementation [Recreated with master updates]
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-publicationListingPage-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-publicationListingPage-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationListingPage.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/labels/listing.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/publications-contentpage.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/checkbox-group-with-filter-count.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/PublicationListingPage.java
  site/components/src/main/java/uk/nhs/hee/web/components/ListingPageType.java
  site/components/src/main/java/uk/nhs/hee/web/components/PublicationListingPageComponent.java
  site/components/src/main/java/uk/nhs/hee/web/components/info/PublicationListingPageComponentInfo.java
  site/components/src/main/java/uk/nhs/hee/web/repository/HEEField.java
  site/components/src/main/java/uk/nhs/hee/web/repository/ValueListIdentifier.java
  site/components/src/test/java/uk/nhs/hee/web/components/ListingPageTypeTest.java
  site/components/src/test/java/uk/nhs/hee/web/repository/HEEFieldTest.java
  site/components/src/test/java/uk/nhs/hee/web/repository/ValueListIdentifierTest.java
Labels: enhancement

#318 NWPS-1257-Search Feature results bugfix
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
Labels: bugfix

#302 NWPS-1161-right-side-boxes-on-the-publication-page
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/utils/document-formats.ftl
  site/components/src/main/java/uk/nhs/hee/web/components/ReportComponent.java
  site/components/src/main/java/uk/nhs/hee/web/utils/HstUtils.java
  site/components/src/main/java/uk/nhs/hee/web/utils/ReportAndPublicationUtils.java
Labels: enhancement

#320 NWPS-1250 Dental Recruitment Redirects
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain_with_preview.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain_with_preview.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/hometodentaltraineerecruitment.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/searchtosearchresultsredirect.yaml
Labels: enhancement

#322 NWPS-1161 Bugfix removing text opens in new window on free marker files
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/file-links-card.ftl
Labels: bugfix

#321 Revert "NWPS-1257-Search Feature results bugfix"
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/searchresults-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/list-item.ftl
Labels: WIP

#325 NWPS-1280 Dental recruitment redirect url changes
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_bloomreach_domain_with_preview.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/dental/dental_recruitment_redirects_hee_nhs_uk_domain_with_preview.yaml
Labels: enhancement

#324 NWPS-1209: CI/CD GitHub actions upgrade
  .github/workflows/ci.yml
  .github/workflows/cicd-release.yml
  .github/workflows/cicd.yml
Labels: upgrade

#288 NWPS-1092 & NWPS-1287: 'Author' content model build and FE integration
  cms/src/main/java/uk/nhs/hee/web/validation/validator/UniqueAuthorValidator.java
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-author-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-author-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/author.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/blogposts.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/news.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/author-cards.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/utils/author-util.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/Author.java
  site/components/src/main/java/uk/nhs/hee/web/beans/BlogPost.java
  site/components/src/main/java/uk/nhs/hee/web/beans/News.java
  site/components/src/main/java/uk/nhs/hee/web/beans/PublicationLandingPage.java
Labels: enhancement

#327 NWPS-922-1165 Newsletter bugfixes
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/newsletter-subscribe-form.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
Labels: bugfix

#326 NWPS-1347-BE-Right-side-Publication-Info-box-for-Publication-Single-Page
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
  site/components/src/main/java/uk/nhs/hee/web/components/ReportComponent.java
Labels: enhancement

#331 NWPS-1160 Publication Info Box for Publication Landing Page
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlisting-main.ftl
  site/components/src/main/java/uk/nhs/hee/web/components/PublicationLandingPageComponent.java
  site/components/src/main/java/uk/nhs/hee/web/components/ReportComponent.java
Labels: enhancement

#330 NWPS-1092: Author by Person XPath query Improvement
  cms/src/main/java/uk/nhs/hee/web/validation/validator/UniqueAuthorValidator.java
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
Labels: enhancement

#329 NWPS- 1325, NWPS-1326, NWPS-1327 & NWPS-1361: Banner content model enhancement and FE integration
  cms/src/main/java/uk/nhs/hee/web/validation/validator/BannerPhaseNameValidator.java
  cms/src/main/resources/website-blueprint/config/domains/channel-content.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-dental.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-digital-transformation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-health-careers.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-lks.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-medical.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-quality.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-website-testing.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-subsite.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/banner.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/phasebannernames.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/dental/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/digital-transformation/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/health-careers/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/lks/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/medical/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/quality/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/website-testing/settings.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/settings/banners/alert-banner.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/settings/banners/announcement-banner.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/settings/banners/mourning-banner.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/settings/banners/phase-banner.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/site-banner.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/common/abstractpages/base.yaml
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-banner.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/layout/base-layout.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/Banner.java
  site/components/src/main/java/uk/nhs/hee/web/components/BannerComponent.java
  site/components/src/main/java/uk/nhs/hee/web/content/rewriter/impl/BannerContentRewriter.java
  site/components/src/test/java/uk/nhs/hee/web/content/rewriter/impl/BannerContentRewriterTest.java
Labels: enhancement

#332 [NWPS-1331] Impl. of 'Hide Author contact details' checkbox toggle for Blog post, News and Publication landing pages
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/publicationLandingPage.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/news.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/author-cards.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/BlogPost.java
  site/components/src/main/java/uk/nhs/hee/web/beans/News.java
  site/components/src/main/java/uk/nhs/hee/web/beans/PublicationLandingPage.java
Labels: enhancement

#333 NWPS-1340-1341 Enhancement/nwps 1340 fei publications single page
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/publicationlandingpage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/headings-toc.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.js
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
Labels: enhancement

#337 [NWPS-1368] Author: Change Bio to Text field
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/author.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/person-author.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/Author.java
Labels: enhancement

#341 NWPS-1287: Author image height bug FE integration
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
Labels: bug

#340 [NWPS-1340]: Publication page document type and freemarker updates
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/publications.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
Labels: enhancement
