Repository Health-Education-England/hee-cms-platform, pull requests merged in 2023-05, with the labels that each got.

#396 NWPS-1499-Create-new-channel-to-support-alpha-project
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-wte-alpha-assets-and-gallery-readwrite.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/domains/content-wte-alpha.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/groups/wte-alpha-author.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/groups/wte-alpha-editor.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/groups/wte-alpha-viewer.yaml
  repository-data/application/src/main/resources/hcm-content/content/assets/wte-alpha.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/wte-alpha.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/wte-alpha/settings.yaml
  repository-data/application/src/main/resources/hcm-content/content/gallery/wte-alpha.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/wte-alpha/home.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/components.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/pages.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/sitemap.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace/channel.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace/pages.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations/wte-alpha/workspace/sitemap.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts/br-cloud/cloud.yaml
  repository-data/site/src/main/resources/hcm-content/hst/configurations/wte-alpha/workspace/channel/channelinfo.yaml
  repository-data/site/src/main/resources/hcm-content/hst/sites/wte-alpha.yaml
  site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
Labels: enhancement

#395 [NWPS-1497] Search component update to return 406 [Not Acceptable] error response for invalid keywords
  repository-data/site/src/main/resources/hcm-config/hst/configurations/common/pages/searchresults.yaml
  site/components/src/main/java/uk/nhs/hee/web/components/SearchResultsComponent.java
Labels: bugfix

#391 [NWPS-1477] Including commented KLS Rebuild non-channel-specific value-lists for completeness
  site/components/src/main/resources/META-INF/hst-assembly/overrides/valueListManager.xml
Labels: bugfix

#393 [NWPS-1128] Advanced search plugin added
  cms-dependencies/pom.xml
  repository-data/application/src/main/resources/hcm-config/configuration/frontend/cms.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/cms.yaml
Labels: enhancement

#399 [NWPS-1505] Quote block missing fix to minihub pages
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
Labels: bugfix

#400 [NWPS-1127] Tagging plugin for standard content pages
  cms-dependencies/pom.xml
  essentials/src/main/resources/taggingPlugin.xml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/digital-transformation/digital-academy.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/a-to-z-test-content.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/cookies.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
  site/components/src/main/java/uk/nhs/hee/web/beans/Guidance.java
Labels: enhancement

#386 [NWPS-1450] [NWPS-1436] BE-New-Expander-Table-content-block
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-expanderTable-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-expanderTable-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/HomePage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/blogPage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/expander.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/expanderTable.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/expanderTableReference.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/expanderTableRow.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/guidanceDocument.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/news.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/report.yaml
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/kls-rebuild/searchtosearchresultsredirect.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/guidance-pages.yaml
  repository-data/webfiles/src/main/resources/site/css/hee.css
  repository-data/webfiles/src/main/resources/site/css/hee.min.css
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/blogpost-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/news-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/report-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/components.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/expander-table.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/macros/guidance-content.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/homepage-main.ftl
  repository-data/webfiles/src/main/resources/site/freemarker/hee/pages/minihub-main.ftl
  repository-data/webfiles/src/main/resources/site/js/hee.js
  repository-data/webfiles/src/main/resources/site/js/hee.min.js
  site/components/src/main/java/uk/nhs/hee/web/beans/Expander.java
  site/components/src/main/java/uk/nhs/hee/web/beans/ExpanderTable.java
  site/components/src/main/java/uk/nhs/hee/web/beans/ExpanderTableReference.java
  site/components/src/main/java/uk/nhs/hee/web/beans/ExpanderTableRow.java
Labels: enhancement, bugfix

#398 [NWPS-1289] Alt text taken from description and is now mandatory for images
  cms/src/main/java/uk/nhs/hee/web/repository/gallery/impl/HEEGalleryWorkflowImpl.java
  cms/src/main/java/uk/nhs/hee/web/repository/gallery/impl/HEEGalleryWorkflowImpl.properties
  repository-data/application/src/main/resources/hcm-config/configuration/workflows/gallery.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/imagesetWithCaption.yaml
Labels: enhancement

#406 [NWPS-1440] Enhancement/nwps 1440 search bank valuelist updates
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/lks/searchbanktopics.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts/br-cloud/cloud.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts/dev-localhost-docker/internal.yaml
  repository-data/site/src/main/resources/hcm-config/hst/hosts/prd-live/uk.yaml
Labels: enhancement

#407 [NWPS-939] Text find replace plugin
  cms-dependencies/pom.xml
  pom.xml
Labels: enhancement

#409 [NWPS-1402] Renamed remaining content blocks
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
Labels: enhancement

#408 [NWPS-1478] Case Study Sectors values list updates
  repository-data/application/src/main/resources/hcm-actions.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/administration/valuelists/lks/casestudysectors.yaml
Labels: enhancement

#414 [NWPS-1516] Url redirects for Ives review pages - Digital Transformation
  repository-data/application/src/main/resources/hcm-content/content/urlrewriter/digital-transformation/philipsivesreviewpages.yaml
Labels: enhancement

#403 [NWPS-1444] A-Z listing tidy up
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/common.yaml
  repository-data/development/src/main/resources/hcm-content/content/documents/lks/visual-regression.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/pages/visual-regression-vr-a-z-listing-page-contentpage.yaml
  repository-data/site-development/src/main/resources/hcm-content/hst/configurations/lks/workspace/sitemap/visual-regression.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/atozlisting-main.ftl
  visual-regression/backstop.js
Labels: front-end

#416 NWPS-1409-be-training-programme-page-new
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-training-programmepage-document.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/queries/templates/new-training-programmepage-folder.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/templates.yaml
  repository-data/application/src/main/resources/hcm-config/configuration/translations/types.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee-cms-platform.cnd
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammePage.yaml
  repository-data/application/src/main/resources/hcm-config/namespaces/hee/trainingProgrammesHomepage.yaml
  repository-data/application/src/main/resources/hcm-content/content/documents/lks/training-programmes-pages.yaml
  repository-data/site/src/main/resources/hcm-config/hst/configurations.yaml
  repository-data/webfiles/src/main/resources/site/freemarker/hee/catalog/trainingProgrammePage-main.ftl
  site/components/src/main/java/uk/nhs/hee/web/beans/TrainingProgrammePage.java
  site/components/src/main/java/uk/nhs/hee/web/components/TrainingProgrammePageComponent.java
  site/components/src/main/java/uk/nhs/hee/web/components/info/TrainingProgrammePageComponentInfo.java
Labels: enhancement

#420 [NWPS-910] Google map embed code regex update to restrict multiple occurrences of iframe embed codes
  repository-data/application/src/main/resources/hcm-config/configuration/modules/validation.yaml
Labels: bugfix
